# Generated by Django 2.2 on 2020-01-26 11:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('features', '0002_feature_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=10, max_digits=6, null=True),
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('contributed_on', models.DateTimeField(default=datetime.datetime.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='features.Feature')),
            ],
        ),
    ]
