# Generated by Django 2.2 on 2020-02-23 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('features', '0005_auto_20200222_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='feature',
            name='likes',
        ),
        migrations.DeleteModel(
            name='Contribution',
        ),
        migrations.AddField(
            model_name='like',
            name='feature',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='features.Feature'),
        ),
        migrations.AddField(
            model_name='like',
            name='users',
            field=models.ManyToManyField(related_name='requirement_feature_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dislike',
            name='feature',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dis_likes', to='features.Feature'),
        ),
        migrations.AddField(
            model_name='dislike',
            name='users',
            field=models.ManyToManyField(related_name='requirement_feature_dis_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
