# Generated by Django 2.2 on 2020-02-23 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0006_auto_20200223_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='feature',
        ),
        migrations.RemoveField(
            model_name='like',
            name='users',
        ),
        migrations.DeleteModel(
            name='DisLike',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
