# Generated by Django 2.2 on 2020-01-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0002_auto_20200118_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='slug',
            field=models.SlugField(default='', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='bug',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
