# Generated by Django 2.2 on 2020-01-04 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='status',
            field=models.IntegerField(choices=[('Received', 'Received'), ('In progress', 'In progress'), ('Done', 'Done')], default='Received'),
        ),
    ]
