# Generated by Django 2.2 on 2020-01-18 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0004_auto_20200118_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='slug',
        ),
    ]
