# Generated by Django 2.2 on 2020-01-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0004_auto_20200104_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='status',
            field=models.IntegerField(choices=[(0, 'Received'), (1, 'In progress'), (2, 'Done')], default='Received'),
        ),
    ]
