# Generated by Django 2.2 on 2020-01-04 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0005_auto_20200104_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='status',
            field=models.CharField(choices=[(0, 'Received'), (1, 'In progress'), (2, 'Done')], default='Received', max_length=15),
        ),
    ]
