# Generated by Django 2.2 on 2020-01-04 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0006_auto_20200104_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='status',
            field=models.CharField(choices=[('Received', 'Received'), ('In progress', 'In progress'), ('Done', 'Done')], default='Received', max_length=15),
        ),
    ]
