# Generated by Django 2.2 on 2020-01-18 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0006_buglikes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BugLikes',
        ),
    ]
