# Generated by Django 2.2 on 2020-01-18 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0007_delete_buglikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='likes',
        ),
        migrations.AddField(
            model_name='bug',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
